apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: rhel9
  namespace: simple-vm  
spec:
  selector:
    matchExpressions:
      - key: app  
        operator: In
        values:
        - rhel9 
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription
