apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: windows11-installer-run-
spec:
  params:
    - name: winImageDownloadURL
      value: >-
        http://installhost.example.com:8080/win11.iso
    - name: autounattendConfigMapName
      value: windows11-autounattend
    - name: sourceTemplateName
      value: windows11-desktop-large
    - name: sourceTemplateNamespace
      value: openshift
    - name: installerTemplateName
      value: windows11-desktop-large-installer
    - name: allowReplaceInstallerTemplate
      value: 'true'
    - name: baseDvName
      value: win11
    - name: baseDvNamespace
      value: openshift-virtualization-os-images
    - name: isoDVName
      value: win11
    - name: allowReplaceISODV
      value: 'false'
  pipelineRef:
    name: windows-efi-installer
  timeout: 1h0m0s
  taskRunSpecs:
    - pipelineTaskName: "modify-windows-iso-file"
      taskPodTemplate:
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          fsGroup: 1001          
