apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  creationTimestamp:
  name: lvms-operator
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: stable-4.13
  installPlanApproval: Automatic
  name: lvms-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
status: {}
